Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  DefaultDescLen: 100
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

Database:
  DBType: mysql
  Username: root
  Password: 486942
  Host: joklr.org:3306
  DBName: forum
  Charset: utf8
  ParseTime: True
  MaxIdleconns: 10
  MaxOpenConns: 30

JWT:
  Secret: asldjflasd
  Issuer: a3-group
  Expire: 7200